import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Remove 'buffer' and 'crypto' from builtins so they get bundled.
// 'buffer'  — replaced by polyfill_buffer.js (injected globally).
// 'crypto'  — replaced by polyfill_node_crypto.js via the alias below.
// On Android, Obsidian throws "Attempting to load NodeJS package: <name>"
// for ANY Node.js builtin that reaches a require() at runtime, so these two
// must never appear as external requires in the bundle.
const externalBuiltins = builtinModules.filter(
	(m) => m !== "buffer" && m !== "crypto",
);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	inject: ["./src/polyfills/buffer.js"],
	alias: {
		// Redirect require("crypto") to a pure-JS polyfill so Android Obsidian
		// does not throw "Attempting to load NodeJS package: crypto".
		crypto: "./src/polyfills/node-crypto.js",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...externalBuiltins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	outfile: "main.js",
	platform: "browser",
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
		global: "globalThis",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
