import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Remove 'buffer' from builtins so it gets bundled (needed for mobile polyfill)
const externalBuiltins = builtinModules.filter((m) => m !== "buffer");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	inject: ["./polyfill_buffer.js"],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...externalBuiltins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "browser",
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
		global: "globalThis",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
